version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/proxy/certs:/etc/nginx/certs:ro 
    labels: 
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    environment:
      - ENABLE_IPV6=true
      - HTTPS_METHOD=noredirect

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
      - CERT_NAME=whoami.local

  bouncer:
    hostname: docker-bouncer.local
#    container_name: bouncer
    domainname: local 
    image: outcomelife/bouncer:latest
    links:
      - bouncerdb:db
    volumes:
      - ./importexport:/opt/jboss/backup
    environment:
      - VIRTUAL_HOST=docker-bouncer.local
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - VIRTUAL_NETWORK=nginx-proxy
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=551Realm
      - MYSQL_PORT_3306_TCP_ADDR=db
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=keycloakdb
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=551Realm
#      - IMPORTEXPORT=IMPORT
    ports:
      - "28080:8080"
  bouncerdb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=keycloakdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=551Realm
      - MYSQL_ROOT_PASSWORD=551Realm
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=551Realm
    restart: always
