FROM alpine:3.6 as packager
MAINTAINER Adam Crow <acrow@crowtech.com.au>
ADD jdk-9-ea+181_linux-x64-musl_bin.tar /opt/
# Build our own jdk9 distro with only these modules, as first stage
RUN /opt/jdk-9/bin/jlink \
    --module-path /opt/jdk-9/jmods \
    --verbose \
    --add-modules java.base,java.logging,java.xml,jdk.unsupported \
    --compress 2 \
    --no-header-files \
    --output /opt/jdk-9-minimal

# Second stage, add only our custom jdk9 distro and our app
FROM alpine:3.6
COPY --from=packager /opt/jdk-9-minimal /opt/jdk-9-minimal

ENV JAVA_HOME=/opt/jdk-9-minimal
ENV PATH="$PATH:$JAVA_HOME/bin"


RUN apt update && apk add jq && apk add curl && apk add bash && apk add xmlstarlet && apk add wget && apk add vim && apk add unzip && apk add sed
RUN echo http://mirror.yandex.ru/mirrors/alpine/v3.7/main > /etc/apk/repositories; \
    echo http://mirror.yandex.ru/mirrors/alpine/v3.7/community >> /etc/apk/repositories

ENV HOME /opt/jboss
ENV WILDFLY_VERSION 12.0.0.Final
#ENV WILDFLY_VERSION 10.1.0.Final
ENV KEYCLOAK_VERSION 3.4.3.Final
ENV MYSQLCONNECTOR_VERSION 5.1.41

# Enables signals getting passed from startup script to JVM
# ensuring clean shutdown when container is stopped.
ENV LAUNCH_JBOSS_IN_BACKGROUND 1
ENV MYSQL_PORT_3306_TCP_PORT 3306

USER root

RUN mkdir -p /opt/jboss
RUN chown -R root:root $HOME 

COPY java/* /usr/share/java/

USER root 
ENV JBOSS_HOME $HOME/wildfly

#RUN echo "http://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.zip -O $HOME/wildfly.zip | tar zx && mv $HOME/keycloak-$WILDFLY_VERSION $JBOSS_HOME"
RUN cd /opt/jboss/ && curl -L http://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.zip -o $HOME/wildfly.zip
RUN unzip $HOME/wildfly.zip -d $HOME
RUN mv $HOME/wildfly-$WILDFLY_VERSION $JBOSS_HOME
ADD docker-entrypoint.sh $HOME/
RUN rm -f $HOME/wildfly.zip
RUN cp -f $JBOSS_HOME/standalone/configuration/standalone-full.xml $JBOSS_HOME/standalone/configuration/standalone.xml

ADD setLogLevel.xsl $JBOSS_HOME/
RUN java -jar /usr/share/java/saxon.jar -s:$JBOSS_HOME/standalone/configuration/standalone.xml -xsl:$JBOSS_HOME/setLogLevel.xsl -o:$JBOSS_HOME/standalone/configuration/standalone.xml


USER root

WORKDIR $HOME 

############################ Database #############################
ADD changeDatabase.xsl $JBOSS_HOME/
RUN java -jar /usr/share/java/saxon.jar -s:$JBOSS_HOME/standalone/configuration/standalone.xml -xsl:$JBOSS_HOME/changeDatabase.xsl -o:$JBOSS_HOME/standalone/configuration/standalone.xml; java -jar /usr/share/java/saxon.jar -s:$JBOSS_HOME/standalone/configuration/standalone-ha.xml -xsl:$JBOSS_HOME/changeDatabase.xsl -o:$JBOSS_HOME/standalone/configuration/standalone-ha.xml; 
RUN mkdir -p $JBOSS_HOME/modules/system/layers/base/com/mysql/jdbc/main; cd $JBOSS_HOME/modules/system/layers/base/com/mysql/jdbc/main && curl -O http://central.maven.org/maven2/mysql/mysql-connector-java/$MYSQLCONNECTOR_VERSION/mysql-connector-java-$MYSQLCONNECTOR_VERSION.jar

ADD module.xml $JBOSS_HOME/modules/system/layers/base/com/mysql/jdbc/main/
RUN sed -i "s/mysql-connector-java/mysql-connector-java-$MYSQLCONNECTOR_VERSION/g" $JBOSS_HOME/modules/system/layers/base/com/mysql/jdbc/main/module.xml
RUN sed -i 's/ExampleDS/gennyDS/g' $JBOSS_HOME/standalone/configuration/standalone.xml

############################ Security #############################
#Add Keycloak Support
WORKDIR $JBOSS_HOME
RUN wget http://downloads.jboss.org/keycloak/$KEYCLOAK_VERSION/adapters/keycloak-oidc/keycloak-wildfly-adapter-dist-$KEYCLOAK_VERSION.zip  -O $JBOSS_HOME/keycloak-wildfly-adapter-dist.zip
RUN unzip -o $JBOSS_HOME/keycloak-wildfly-adapter-dist.zip 
RUN rm -Rf keycloak-wildfly-adapter-dist.zip

############################ Node Identifier #############################
#ADD node-identifier.xsl $JBOSS_HOME/
#RUN java -jar /usr/share/java/saxon.jar -s:$JBOSS_HOME/standalone/configuration/standalone.xml -xsl:$JBOSS_HOME/node-identifier.xsl -o:$JBOSS_HOME/standalone/configuration/standalone.xml; java -jar /usr/share/java/saxon.jar -s:$JBOSS_HOME/standalone/configuration/standalone-ha.xml -xsl:$JBOSS_HOME/changeDatabase.xsl -o:$JBOSS_HOME/standalone/configuration/standalone-ha.xml; 


ADD execute.sh /
ADD command.cli /
ADD jms.cli /
RUN /execute.sh


#Set up for proxy
RUN xmlstarlet ed -L -i "//*[local-name()='http-listener']"  -t attr -n "proxy-address-forwarding" -v "true"  $JBOSS_HOME/standalone/configuration/standalone.xml

#ADD standalone.xml $JBOSS_HOME/standalone/configuration/standalone.xml

RUN sed -i 's/127.0.0.1/0.0.0.0/g' $JBOSS_HOME/standalone/configuration/standalone.xml

# clean up empty xmlns strings
RUN sed -i 's/xmlns=\"\"//g' $JBOSS_HOME/standalone/configuration/standalone.xml

RUN rm -Rf $JBOSS_HOME/standalone/configuration/standalone_xml_history/current
RUN chown -R root:root $HOME
USER root 

EXPOSE 8080
EXPOSE 9990
EXPOSE 8787
EXPOSE 50293
EXPOSE 8998

ENTRYPOINT [ "/opt/jboss/docker-entrypoint.sh" ]
CMD ["-b", "0.0.0.0"]
